In [ ]:
!wget -O openfoodfacts.csv.gz https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv.gz

--2026-06-20 15:04:54--  https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv.gz
Resolving static.openfoodfacts.org (static.openfoodfacts.org)... 151.115.132.10
Connecting to static.openfoodfacts.org (static.openfoodfacts.org)|151.115.132.10|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://openfoodfacts-ds.s3.eu-west-3.amazonaws.com/en.openfoodfacts.org.products.csv.gz [following]
--2026-06-20 15:04:55--  https://openfoodfacts-ds.s3.eu-west-3.amazonaws.com/en.openfoodfacts.org.products.csv.gz
Resolving openfoodfacts-ds.s3.eu-west-3.amazonaws.com (openfoodfacts-ds.s3.eu-west-3.amazonaws.com)... 16.12.19.42, 52.95.155.44
Connecting to openfoodfacts-ds.s3.eu-west-3.amazonaws.com (openfoodfacts-ds.s3.eu-west-3.amazonaws.com)|16.12.19.42|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1275171186 (1.2G) [application/gzip]
Saving to: ‘openfoodfacts.csv.gz’

openfoodfacts.csv.g 100%[===================>]   1.19G  26.0MB/s    in 47s

2026-06-20 15:05:43 (25.7 MB/s) - ‘openfoodfacts.csv.gz’ saved [1275171186/1275171186]

In [ ]:
import pandas as pd

sample = pd.read_csv(
    "openfoodfacts.csv.gz",
    sep="\t",
    compression="gzip",
    nrows=5,
    low_memory=False
)

print(sample.columns.tolist())

['code', 'url', 'creator', 'created_t', 'created_datetime', 'last_modified_t', 'last_modified_datetime', 'last_modified_by', 'last_updated_t', 'last_updated_datetime', 'product_name', 'abbreviated_product_name', 'generic_name', 'quantity', 'packaging', 'packaging_tags', 'packaging_en', 'packaging_text', 'brands', 'brands_tags', 'brands_en', 'categories', 'categories_tags', 'categories_en', 'origins', 'origins_tags', 'origins_en', 'manufacturing_places', 'manufacturing_places_tags', 'labels', 'labels_tags', 'labels_en', 'emb_codes', 'emb_codes_tags', 'first_packaging_code_geo', 'cities', 'cities_tags', 'purchase_places', 'stores', 'countries', 'countries_tags', 'countries_en', 'ingredients_text', 'ingredients_tags', 'ingredients_analysis_tags', 'allergens', 'allergens_en', 'traces', 'traces_tags', 'traces_en', 'serving_size', 'serving_quantity', 'no_nutrition_data', 'additives_n', 'additives', 'additives_tags', 'additives_en', 'nutriscore_score', 'nutriscore_grade', 'nova_group', 'pnns_groups_1', 'pnns_groups_2', 'food_groups', 'food_groups_tags', 'food_groups_en', 'states', 'states_tags', 'states_en', 'brand_owner', 'environmental_score_score', 'environmental_score_grade', 'nutrient_levels_tags', 'product_quantity', 'owner', 'data_quality_errors_tags', 'unique_scans_n', 'popularity_tags', 'completeness', 'last_image_t', 'last_image_datetime', 'main_category', 'main_category_en', 'image_url', 'image_small_url', 'image_ingredients_url', 'image_ingredients_small_url', 'image_nutrition_url', 'image_nutrition_small_url', 'energy-kj_100g', 'energy-kcal_100g', 'energy_100g', 'energy-from-fat_100g', 'fat_100g', 'saturated-fat_100g', 'butyric-acid_100g', 'caproic-acid_100g', 'caprylic-acid_100g', 'capric-acid_100g', 'lauric-acid_100g', 'myristic-acid_100g', 'palmitic-acid_100g', 'stearic-acid_100g', 'arachidic-acid_100g', 'behenic-acid_100g', 'lignoceric-acid_100g', 'cerotic-acid_100g', 'montanic-acid_100g', 'melissic-acid_100g', 'unsaturated-fat_100g', 'monounsaturated-fat_100g', 'omega-9-fat_100g', 'polyunsaturated-fat_100g', 'omega-3-fat_100g', 'omega-6-fat_100g', 'alpha-linolenic-acid_100g', 'eicosapentaenoic-acid_100g', 'docosahexaenoic-acid_100g', 'linoleic-acid_100g', 'arachidonic-acid_100g', 'gamma-linolenic-acid_100g', 'dihomo-gamma-linolenic-acid_100g', 'oleic-acid_100g', 'elaidic-acid_100g', 'gondoic-acid_100g', 'mead-acid_100g', 'erucic-acid_100g', 'nervonic-acid_100g', 'trans-fat_100g', 'cholesterol_100g', 'carbohydrates_100g', 'sugars_100g', 'added-sugars_100g', 'sucrose_100g', 'glucose_100g', 'fructose_100g', 'galactose_100g', 'lactose_100g', 'maltose_100g', 'maltodextrins_100g', 'psicose_100g', 'starch_100g', 'polyols_100g', 'erythritol_100g', 'isomalt_100g', 'maltitol_100g', 'sorbitol_100g', 'fiber_100g', 'soluble-fiber_100g', 'polydextrose_100g', 'insoluble-fiber_100g', 'proteins_100g', 'casein_100g', 'serum-proteins_100g', 'nucleotides_100g', 'salt_100g', 'added-salt_100g', 'sodium_100g', 'alcohol_100g', 'vitamin-a_100g', 'beta-carotene_100g', 'vitamin-d_100g', 'vitamin-e_100g', 'vitamin-k_100g', 'vitamin-c_100g', 'vitamin-b1_100g', 'vitamin-b2_100g', 'vitamin-pp_100g', 'vitamin-b6_100g', 'vitamin-b9_100g', 'folates_100g', 'vitamin-b12_100g', 'biotin_100g', 'pantothenic-acid_100g', 'silica_100g', 'bicarbonate_100g', 'potassium_100g', 'chloride_100g', 'calcium_100g', 'phosphorus_100g', 'iron_100g', 'magnesium_100g', 'zinc_100g', 'copper_100g', 'manganese_100g', 'fluoride_100g', 'selenium_100g', 'chromium_100g', 'molybdenum_100g', 'iodine_100g', 'caffeine_100g', 'taurine_100g', 'methylsulfonylmethane_100g', 'hydroxymethylbutyrate_100g', 'ph_100g', 'fruits-vegetables-legumes_100g', 'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g', 'carbon-footprint_100g', 'glycemic-index_100g', 'water-hardness_100g', 'choline_100g', 'phylloquinone_100g', 'beta-glucan_100g', 'inositol_100g', 'carnitine_100g', 'sulphate_100g', 'nitrate_100g', 'acidity_100g', 'carbohydrates-total_100g', 'water_100g']

In [ ]:
cols = [
    "product_name",
    "categories_tags",
    "ingredients_text",
    "sugars_100g",
    "proteins_100g",
    "fiber_100g",
    "fat_100g",
    "nutriscore_grade",
    "nova_group"
]

In [ ]:
df = pd.read_csv(
    "openfoodfacts.csv.gz",
    sep="\t",
    compression="gzip",
    usecols=cols,
    nrows=500000,
    low_memory=False
)

In [ ]:
print(df.shape)

(500000, 9)

In [ ]:
df.head()

,product_name,categories_tags,ingredients_text,nutriscore_grade,nova_group,fat_100g,sugars_100g,fiber_100g,proteins_100g
0,Limonade artisanale a la rose,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN
1,M&amp;M white,NaN,"Weizenmehl, Rapsöl, Speisesalz, 1,7% Meersalz,...",unknown,NaN,NaN,NaN,NaN,NaN
2,Chocolate n3,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN
3,Pâte de fruits,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN
4,Paleta gran reserva - Sierra nevada-,"en:beverages-and-beverages-preparations,en:bev...","Thiamin, Biotin, Chromium, Garcinia cambogia f...",unknown,4.0,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   product_name      484211 non-null  object
 1   categories_tags   268078 non-null  object
 2   ingredients_text  266958 non-null  object
 3   nutriscore_grade  498349 non-null  object
 4   nova_group        252080 non-null  float64
 5   fat_100g          115076 non-null  float64
 6   sugars_100g       111635 non-null  float64
 7   fiber_100g        83220 non-null   float64
 8   proteins_100g     115225 non-null  float64
dtypes: float64(5), object(4)
memory usage: 34.3+ MB

In [ ]:
df.isnull().sum().sort_values(ascending=False)

fiber_100g          416780
sugars_100g         388365
fat_100g            384924
proteins_100g       384775
nova_group          247920
ingredients_text    233042
categories_tags     231922
product_name         15789
nutriscore_grade      1651
dtype: int64

In [ ]:
df.describe()

          nova_group      fat_100g   sugars_100g    fiber_100g  proteins_100g
count  252080.000000  1.150760e+05  1.116350e+05  8.322000e+04   1.152250e+05
mean        3.490301  1.647922e+02  8.959110e+04  1.235965e+02   8.723586e+03
std         0.954684  5.174682e+04  2.992952e+07  3.466466e+04   2.945984e+06
min         1.000000  0.000000e+00  0.000000e+00 -1.546239e-01   0.000000e+00
25%         3.000000  6.583761e-01  1.000000e+00  0.000000e+00   2.000000e+00
50%         4.000000  5.000000e+00  4.583333e+00  1.639344e+00   6.060000e+00
75%         4.000000  1.785710e+01  1.600000e+01  3.600000e+00   1.084337e+01
max         4.000000  1.755400e+07  1.000000e+10  1.000000e+07   1.000000e+09

In [ ]:
clean_df = df.copy()

clean_df = clean_df.dropna(
    subset = [
        "product_name",
        "categories_tags",
        "sugars_100g",
        "proteins_100g"
    ])

In [ ]:
# Checking size
print("Before:", len(df))
print("After:", len(clean_df))

Before: 500000
After: 52857

In [ ]:
# Removing impossible nutrition values since values are between 0 and 100 (0-100)
clean_df = clean_df[
    (clean_df["sugars_100g"] >= 0) &
    (clean_df["sugars_100g"] <= 100) &
    (clean_df["proteins_100g"] >= 0) &
    (clean_df["proteins_100g"] <= 100)

]

In [ ]:
clean_df[["sugars_100g", "proteins_100g"]].describe()

        sugars_100g  proteins_100g
count  52746.000000   52746.000000
mean      12.233006       7.987432
std       17.814261       8.846205
min        0.000000       0.000000
25%        1.176471       2.200000
50%        4.800000       6.572770
75%       14.000000      10.344828
max      100.000000     100.000000

In [ ]:
# save the cleaned dataset
clean_df.to_csv("clean_openfoodfacts.csv", index = False)

In [ ]:
clean_df.shape

(52746, 9)

In [ ]:
clean_df.isnull().sum()

product_name            0
categories_tags         0
ingredients_text    12034
nutriscore_grade        0
nova_group          13301
fat_100g               69
sugars_100g             0
fiber_100g           9488
proteins_100g           0
dtype: int64

# Story 2: Category Wrangler

In [ ]:
clean_df.columns

Index(['product_name', 'categories_tags', 'ingredients_text',
       'nutriscore_grade', 'nova_group', 'fat_100g', 'sugars_100g',
       'fiber_100g', 'proteins_100g'],
      dtype='object')

In [ ]:
clean_df["categories_tags"].unique()

array(['en:asian-style-ready-meal',
       'en:beverages-and-beverages-preparations,en:beverages',
       'en:plant-based-foods-and-beverages,en:plant-based-foods,en:condiments,en:spices,en:curry-powder,en:powder,en:sauce-powder',
       ...,
       'en:condiments,en:sauces,en:meal-sauces,en:pasta-sauces,en:tomato-sauces,en:vegetable-sauces,en:tomato-sauces-with-vegetables',
       'en:breakfasts,en:spreads,en:sweet-spreads,en:bee-products,en:farming-products,en:sweeteners,en:honeys,en:lavender-honeys',
       'en:meats-and-their-products,en:meats,en:chicken-and-its-products,en:poultries,en:chickens,en:bbq-chicken,en:sliced-bbq-chicken'],
      dtype=object)

In [ ]:
# Examining the most common value in categories_tags column
from collections import Counter

all_tags = []

for row in clean_df["categories_tags"].dropna():
    all_tags.extend(str(row).split(","))

tag_counts = Counter(all_tags)

pd.DataFrame(
    tag_counts.most_common(50),
    columns=["tag", "count"]
)

                                        tag  count
0        en:plant-based-foods-and-beverages  21743
1                      en:plant-based-foods  20167
2                   en:cereals-and-potatoes  12515
3                                 en:snacks   9067
4                                 en:breads   7153
5                                en:dairies   6797
6                           en:sweet-snacks   6037
7                        en:fermented-foods   5961
8                en:fermented-milk-products   5907
9                               en:desserts   5374
10            en:cereals-and-their-products   5049
11                        en:dairy-desserts   4106
12              en:fermented-dairy-desserts   4024
13                               en:yogurts   3969
14                             en:beverages   3690
15                            en:condiments   3631
16                            en:breakfasts   3343
17     en:fruits-and-vegetables-based-foods   3041
18                                en:sauces   2996
19                                 en:meals   2752
20                    en:biscuits-and-cakes   2613
21                     en:breakfast-cereals   2481
22              en:meats-and-their-products   2358
23                       en:confectioneries   2221
24                          en:salty-snacks   2183
25                          en:frozen-foods   2156
26                            en:appetizers   1993
27                               en:spreads   1918
28                             en:groceries   1864
29                               en:cheeses   1799
30                 en:plant-based-beverages   1708
31                             en:undefined   1643
32                              en:biscuits   1637
33                                 en:meats   1632
34                en:vegetables-based-foods   1571
35  en:beverages-and-beverages-preparations   1547
36                          en:canned-foods   1454
37            en:legumes-and-their-products   1343
38                en:cocoa-and-its-products   1327
39                       en:chips-and-fries   1321
40                   en:plant-based-spreads   1294
41               en:nuts-and-their-products   1270
42                                en:crisps   1247
43                    en:fruits-based-foods   1161
44                                 en:seeds   1123
45                        en:special-breads   1110
46                 en:biscuits-and-crackers   1108
47                                en:pastas   1061
48                        en:prepared-meats   1014
49                               en:candies    921

In [ ]:
# Products that contain snack-related tags
snack_keywords = [
    "snacks",
    "sweet-snacks",
    "salty-snacks",
    "biscuits",
    "biscuits-and-cakes",
    "biscuits-and-crackers",
    "confectioneries",
    "candies",
    "chips-and-fries",
    "crisps",
    "nuts-and-their-products",
    "seeds",
    "breakfast-cereals",
    "bars"
]

In [ ]:
# use the snack-related tags to create a dataframe
snack_df = clean_df[
    clean_df["categories_tags"].str.contains("|".join(snack_keywords), case=False, na=False)
].copy()

In [ ]:
# the counts of each keyword in snack_keyword
for keyword in snack_keywords:
    count = clean_df["categories_tags"].str.contains(
        keyword,
        case=False,
        na=False
    ).sum()

    print(keyword, count)

snacks 9301
sweet-snacks 6038
salty-snacks 2185
biscuits 3064
biscuits-and-cakes 2613
biscuits-and-crackers 1108
confectioneries 2222
candies 1604
chips-and-fries 1321
crisps 1255
nuts-and-their-products 1271
seeds 1160
breakfast-cereals 2481
bars 823

In [ ]:
print(snack_df.shape)

(13987, 9)

In [ ]:
"""# checking values in categories_tags that contain bar
bar_counts = clean_df["categories_tags"].str.contains(
    "bar",
    case=False,
    na=False
).sum()

print("bar_counts: ", bar_counts)"""

'# checking values in categories_tags that contain bar\nbar_counts = clean_df["categories_tags"].str.contains(\n    "bar",\n    case=False,\n    na=False\n).sum()\n\nprint("bar_counts: ", bar_counts)'

In [ ]:
# created mapping dictionary
category_mapping = {
    "Snack Bars": [
        "bar"
    ],

    "Sweet Snacks": [
        "sweet-snacks",
        "confectioneries",
        "candies"
    ],

    "Biscuits & Cookies": [
        "biscuits",
        "biscuits-and-cakes",
        "biscuits-and-crackers"
    ],

    "Salty Snacks": [
        "salty-snacks",
        "crisps",
        "chips-and-fries",
        "salted-snacks",
        "popcorn"
    ],

    "Nuts & Seeds": [
        "nuts-and-their-products",
        "seeds"
    ],

    "Breakfast & Cereal Snacks": [
        "breakfast-cereals"
    ]
}

In [ ]:
# build the assignment function
def assign_category(tags):

    tags = str(tags).lower()

    for category, keywords in category_mapping.items():

        if any(keyword in tags for keyword in keywords):
            return category

    return "General / Unspecified Snacks"

In [ ]:
# applying the function
snack_df["primary_category"] = (
    snack_df["categories_tags"]
    .apply(assign_category)
)

In [ ]:
snack_df["primary_category"].value_counts()

primary_category
Sweet Snacks                    5174
Breakfast & Cereal Snacks       2375
Nuts & Seeds                    2241
Salty Snacks                    1951
Snack Bars                       970
General / Unspecified Snacks     828
Biscuits & Cookies               448
Name: count, dtype: int64

In [ ]:
(
    snack_df["primary_category"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

primary_category
Sweet Snacks                    36.99
Breakfast & Cereal Snacks       16.98
Nuts & Seeds                    16.02
Salty Snacks                    13.95
Snack Bars                       6.94
General / Unspecified Snacks     5.92
Biscuits & Cookies               3.20
Name: proportion, dtype: float64

In [ ]:
snack_df[
    snack_df["primary_category"] == "Other"
]["categories_tags"].head(20).tolist()

[]

# Story 3: Nutrient Matrix

In [ ]:
analysis_df = snack_df.copy()

In [ ]:
analysis_df.groupby("primary_category")[["sugars_100g", "proteins_100g"]].mean().round(2)

                              sugars_100g  proteins_100g
primary_category
Biscuits & Cookies                   5.22           8.64
Breakfast & Cereal Snacks           21.19           9.13
General / Unspecified Snacks        17.49          12.18
Nuts & Seeds                         5.38          13.85
Salty Snacks                         3.63           6.89
Snack Bars                          31.00           9.22
Sweet Snacks                        37.28           5.08

In [ ]:
analysis_df[
    ["sugars_100g", "proteins_100g"]
].describe()

        sugars_100g  proteins_100g
count  13987.000000   13987.000000
mean      22.108174       8.247220
std       21.282509       7.087489
min        0.000000       0.000000
25%        3.448276       4.000000
50%       17.857143       6.666670
75%       35.000000      10.000000
max      100.000000      76.530612

In [ ]:
# I want to measure how many products exist in the target(healthy) quadrant
analysis_df[(analysis_df["proteins_100g"] >= 10)
      & (analysis_df["sugars_100g"] <= 5)].shape

(1657, 10)

In [ ]:
# Checking the dominant category
analysis_df[(analysis_df.proteins_100g >= 10)
      & (analysis_df.sugars_100g <= 5)]["primary_category"].value_counts()

primary_category
Nuts & Seeds                    766
Breakfast & Cereal Snacks       243
General / Unspecified Snacks    172
Biscuits & Cookies              150
Salty Snacks                    149
Sweet Snacks                    142
Snack Bars                       35
Name: count, dtype: int64

In [ ]:
# save the dataset
analysis_df.to_csv("nutrient_matrix_data.csv", index=False)

In [ ]:
from google.colab import files
files.download("nutrient_matrix_data.csv")

In [ ]:
analysis_df.columns.tolist()

['product_name',
 'categories_tags',
 'ingredients_text',
 'nutriscore_grade',
 'nova_group',
 'fat_100g',
 'sugars_100g',
 'fiber_100g',
 'proteins_100g',
 'primary_category']